### ISSUE TITLE
Cấu trúc Folders

### ISSUE THREAD

**Issue by nhatnguyenn** [thanhnguyen3012/alvingro#5]
Về cấu trúc folders hiện tại khá tốt, tuy nhiên bên anh có câu hỏi như sau:

1. Về thư mục storyboard, nó có thuộc UI không em?
2. Thư mục ReuseComponents nếu được đưa vào folder UICommons cùng cấp với UI thì được không?

**Comment by nhatnguyenn** [comment]
1. Về thư mục storyboard, nó có thuộc UI không em?
2. Thư mục ReuseComponents nếu được đưa vào folder UICommons cùng cấp với UI thì được không?

**Comment by nhatnguyenn** [comment]
Về folder Data, em nên chia 1 folder LocalStorage và 1 folder bao gồm Models

**Comment by thanhnguyen3012** [comment]
> Về folder Data, em nên chia 1 folder LocalStorage và 1 folder bao gồm Models

fixed

**Comment by thanhnguyen3012** [comment]
> Về cấu trúc folders hiện tại khá tốt, tuy nhiên bên anh có câu hỏi như sau:
> 
> 1. Về thư mục storyboard, nó có thuộc UI không em?
> 2. Thư mục ReuseComponents nếu được đưa vào folder UICommons cùng cấp với UI thì được không?

Fixed
